backend:
  name: git-gateway
  branch: master
  accept_roles: #optional - accepts all users if left out
    - admin
    - editor

media_folder: static/img
public_folder: /img

publish_mode: editorial_workflow

collections:
  - name: "blog"
    label: "Blog"
    folder: "src/pages/blog"
    create: true
    slug: "{{year}}-{{month}}-{{day}}-{{slug}}"
    fields:
      - {label: "Template Key", name: "templateKey", widget: "hidden", default: "blog-post"}
      - {label: "Title", name: "title", widget: "string"}
      - {label: "Publish Date", name: "date", widget: "datetime"}
      - {label: "Description", name: "description", widget: "text"}
      - {label: "Body", name: "body", widget: "markdown"}
      - {label: "Tags", name: "tags", widget: "list"}

  - name: "pages"
    label: "Pages"
    files:
      - file: "src/pages/about/index.md"
        label: "About"
        name: "about"
        fields:
          - {label: "Template Key", name: "templateKey", widget: "hidden", default: "about-page"}
          - {label: "Title", name: "title", widget: "string"}
          - {label: "Body", name: "body", widget: "markdown"}
      - file: "src/pages/products/index.md"
        label: "Products Page"
        name: "products"
        fields:
          - {label: "Template Key", name: "templateKey", widget: "hidden", default: "product-page"}
          - {label: Title, name: title, widget: string}
          - {label: Image, name: image, widget: image}
          - {label: Heading, name: heading, widget: string}
          - {label: Description, name: description, widget: string}
          - {label: Intro, name: intro, widget: object, fields: [{label: Heading, name: heading, widget: string}, {label: Description, name: description, widget: text}, {label: Blurbs, name: blurbs, widget: list, fields: [{label: Image, name: image, widget: image}, {label: Text, name: text, widget: text}]}]}
          - {label: Main, name: main, widget: object, fields: [{label: Heading, name: heading, widget: string}, {label: Description, name: description, widget: text}, {label: Image1, name: image1, widget: object, fields: [{label: Image, name: image, widget: image}, {label: Alt, name: alt, widget: string}]}, {label: Image2, name: image2, widget: object, fields: [{label: Image, name: image, widget: image}, {label: Alt, name: alt, widget: string}]}, {label: Image3, name: image3, widget: object, fields: [{label: Image, name: image, widget: image}, {label: Alt, name: alt, widget: string}]}]}
          - {label: Testimonials, name: testimonials, widget: list, fields: [{label: Quote, name: quote, widget: string}, {label: Author, name: author, widget: string}]}
          - {label: Full_image, name: full_image, widget: image}
          - {label: Pricing, name: pricing, widget: object, fields: [{label: Heading, name: heading, widget: string}, {label: Description, name: description, widget: string}, {label: Plans, name: plans, widget: list, fields: [{label: Plan, name: plan, widget: string}, {label: Price, name: price, widget: string}, {label: Description, name: description, widget: string}, {label: Items, name: items, widget: list}]}]}
      - file: "src/pages/home/index.md"
        label: "Home"
        name: "home"
        fields:
          - {label: "Template Key", name: "templateKey", widget: "hidden", default: "home-page"}
          - {label: Titre, name: titre, widget: string}
          - {label: Sous_titre, name: sous_titre, widget: string, required: false}
          - {label: Image_intro, name: image_intro, widget: image}
          - {label: Qui, name: section_qui, widget: object, fields: [
              {label: Texte_bouton, name: texte_bouton, widget: string, required: false}, 
              {label: Titre, name: titre, widget: string, required: false}, 
              {label: Parties, name: parties, widget: list, fields: [
                {label: Title, name: titre, widget: string}, 
                {label: Texte, name: texte, widget: markdown}, 
                {label: Images, name: images, widget: list, fields: [
                  {label: Image, name: image, widget: image}, 
                  {label: Legende, name: legende, widget: string}, 
                  {label: Lien_Youtube, name: lien_youtube, widget: string}
                ]}
              ]},
              {label: Parrains, name: parrains, widget: object, fields: [
                {label: Titre, name: titre, widget: string, required: false},
                {label: Texte_Intro, name: texte_intro, widget: markdown, required: false},
                {label: Texte_Outro, name: texte_outro, widget: markdown, required: false},
                {label: Texte_autre_parrains, name: texte_autre_parrains, widget: markdown, required: false},
                {label: Parrains, name: parrains, widget: list, fields: [
                  {label: Nom, name: nom, widget: string},
                  {label: Mettre_en_avant, name: mettre_en_avant, widget: boolean, default: false},
                  {label: Type, name: type, widget: string, default: "Parrain officiel"},
                  {label: Metier, name: metier, widget: string},
                  {label: Image, name: image, widget: image}, 
                  {label: Lien_Youtube, name: lien_youtube, widget: string}
                ]},
                {label: Images, name: images, widget: list, fields: [
                  {label: Image, name: image, widget: image}, 
                  {label: Legende, name: legende, widget: string}, 
                  {label: Lien_Youtube, name: lien_youtube, widget: string}
                ]}
              ]}
            ]}
          - {label: Quoi, name: section_quoi, widget: object, fields: [
              {label: Texte_bouton, name: texte_bouton, widget: string, required: false}, 
              {label: Titre, name: titre, widget: string, required: false}, 
              {label: Parties, name: parties, widget: list, fields: [
                {label: Title, name: titre, widget: string}, 
                {label: Texte, name: texte, widget: markdown}, 
                {label: Images, name: images, widget: list, fields: [
                  {label: Image, name: image, widget: image}, 
                  {label: Legende, name: legende, widget: string}, 
                  {label: Lien_Youtube, name: lien_youtube, widget: string}
                ]}
              ]},
          ]}
          - {label: Comment, name: section_comment, widget: object, fields: [
              {label: Texte_bouton, name: texte_bouton, widget: string, required: false}, 
              {label: Titre, name: titre, widget: string, required: false}, 
              {label: Parties, name: parties, widget: list, fields: [
                {label: Title, name: titre, widget: string}, 
                {label: Texte, name: texte, widget: markdown}, 
                {label: Images, name: images, widget: list, fields: [
                  {label: Image, name: image, widget: image}, 
                  {label: Legende, name: legende, widget: string}, 
                  {label: Lien_Youtube, name: lien_youtube, widget: string}
                ]}
              ]},
          ]}
          - {label: Participer, name: section_participer, widget: object, fields: [
              {label: Texte_bouton, name: texte_bouton, widget: string, required: false}, 
              {label: Titre, name: titre, widget: string, required: false}, 
              {label: Parties, name: parties, widget: list, fields: [
                {label: Title, name: titre, widget: string}, 
                {label: Texte, name: texte, widget: markdown}, 
                {label: Images, name: images, widget: list, fields: [
                  {label: Image, name: image, widget: image}, 
                  {label: Legende, name: legende, widget: string}, 
                  {label: Lien_Youtube, name: lien_youtube, widget: string}
                ]}
              ]},
          ]}
     